//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamQuestionPool.Models
{
    using System;
    using System.Collections.Generic;
    //
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblQuestionPool
    {
        [DisplayName("題目編號")]
        [Required(ErrorMessage = "不可空白")]
        public int fQuestionID { get; set; }

        [DisplayName("題目描述")]
        //[Required(ErrorMessage = "不可空白")]
        public string fQuestion { get; set; }

        [DisplayName("選項(A)")]
        //[Required(ErrorMessage = "不可空白")]
        public string fChoice1 { get; set; }

        [DisplayName("選項(B)")]
        //[Required(ErrorMessage = "不可空白")]
        public string fChoice2 { get; set; }

        [DisplayName("選項(C)")]
        //[Required(ErrorMessage = "不可空白")]
        public string fChoice3 { get; set; }

        [DisplayName("選項(D)")]
        //[Required(ErrorMessage = "不可空白")]
        public string fChoice4 { get; set; }

        [DisplayName("正確答案")]
        //[Required(ErrorMessage = "不可空白")]
        public string fAnswer { get; set; }
    }
}
